### ISSUE TITLE
JSON.stringnify missing in localstorage.setItem 

### ISSUE THREAD

**Issue by mromanoff** [mobxjs/mobx-react-todomvc#13]
I think you missing JSON.stringnify({todos}) in setItem second param:

`
subscribeLocalstorageToStore() {
		reaction(
			() => this.toJS(),
			todos => localStorage.setItem('mobx-react-todomvc-todos', todos)
		);
	}
`

should be:

`subscribeLocalstorageToStore() {
		reaction(
			() => this.toJS(),
			todos => localStorage.setItem('mobx-react-todomvc-todos', JSON.stringify({todos}))
		);
	}`

**Comment by mweststrate** [comment]
Wow, got the notification for this issue only today. Anyway, I'm pretty sure you're right. Could you verify & test and do a small create a PR? That would be awesome :-D

**Comment by mromanoff** [comment]
@mweststrate sorry for delay. here is pull request fix to subscribeLocalstorageToStore #14. Please review and close pull request. I know I can do that myself but i prefer you to review it first. ;-)
