### ISSUE TITLE
Exception when adding new todo items with dev tools logging enabled

### ISSUE THREAD

**Issue by chrisrichard** [mobxjs/mobx-react-todomvc#17]
- start app
- enable state change logging via dev tools button
- add new todo item

![image](https://cloud.githubusercontent.com/assets/1100888/26517869/1df453e0-4270-11e7-996e-16a62377a9a2.png)

**Comment by chrisrichard** [comment]
Related to expr in todoItem.js. Removing expr makes the problem go away.

**Comment by andykog** [comment]
@mweststrate

**Comment by andykog** [comment]
Fixed in `mobx-react-devtools@4.2.15` via https://github.com/mobxjs/mobx-react-devtools/commit/8de7b25ba632bfb8a43204e4218ecca951ccd001 won't thow anymore (and won't print object's name)
