### ISSUE TITLE
TodoStore

### ISSUE THREAD

**Issue by hnordt** [mobxjs/mobx-react-todomvc#3]
Hello.

I'm coming from Redux and I'm still newbie to MobX. It's impressive.

I have a question: https://github.com/mobxjs/mobx-react-todomvc/blob/master/src/stores/todoModel.js

I'll keep the semantics if I rename `TodoModel` to `TodoStore`, `Todo` to `TodoModel` and the file `todoModel.js` to `TodoStore.js`?

**Comment by mweststrate** [comment]
@hnordt Yes, and that sounds like a logical rename indeed :)

**Comment by hnordt** [comment]
Awesome, may I open a pull request to rename it?

**Comment by mweststrate** [comment]
Sure :)

Op wo 13 apr. 2016 om 17:47 schreef Héliton Nordt <notifications@github.com

**Comment by hnordt** [comment]
https://github.com/mobxjs/mobx-react-todomvc/pull/5
